### ISSUE TITLE
class Phpfastcache\Helper\Psr16Adapter

### ISSUE THREAD

**Issue by hosein79** [postaddictme/instagram-php-scraper#817] opened 2020-11-22 19:34 UTC
Hi, I have a problem with this line
This is what I write
use Phpfastcache \ Helper \ Psr16Adapter;
This shows the error
Fatal error: Uncaught Error: Class 'Phpfastcache\Helper\Psr16Adapter' not found in D:\Wamp\www................................

**Comment by NimaN2D** [comment] 2020-12-19 09:48
`composer require phpfastcache/phpfastcache`

**Comment by NimaN2D** [comment] 2020-12-19 09:49
Duplicate of #558

**Comment by NimaN2D** [comment] 2020-12-19 09:50
Duplicate of #558
Google.com is your best friend <3

**Closed** 2021-06-16 23:14 UTC
Labels: wontfix
