### ISSUE TITLE
biography returns NULL

### ISSUE THREAD

**Issue by kirillantv** [postaddictme/instagram-php-scraper#136] opened 2017-07-11 19:39 UTC
biography in user's data returns NULL. I have the latest update of your repo. I can't understand what's the problem. Is this problem not only mine? What's solution? 

The problem is in getAccountById function. It is returns user data as media using function fromMediaPage(). Is it normal?

**Comment by e-beach** [comment] 2017-07-11 23:27
Yes the function is not working. I'm working on a fix for this.

**Comment by e-beach** [comment] 2017-07-12 00:04
Actually, no, the problem is biography is null in the JSON response. Probably the user does not have a biography at all.

**Comment by danwoodbury** [comment] 2017-08-29 11:46
I am also facing this issue and I know for a fact that the user I am searching for has a biography on their account

**Comment by raiym** [comment] 2017-11-08 14:10
It has been fixed

**Closed by raiym** 2017-11-08 14:10 UTC
