### ISSUE TITLE
getMediaCommentsByCode only returning 50 comments max

### ISSUE THREAD

**Issue by faiq-naseem** [postaddictme/instagram-php-scraper#358] opened 2018-04-22 06:38 UTC
How can I get all comments?
$comments = $instagram->getMediaCommentsByCode('Bhv085lH1n-',50);

**Comment by levicosta201** [comment] 2018-05-03 04:48
I'm also having this same problem and I can not solve

**Comment by RainGrid** [comment] 2018-06-03 19:50
Duplicate of #379

**Closed** 2019-04-24 12:59 UTC
Labels: wontfix
