### ISSUE TITLE
Account with this username does not exist

### ISSUE THREAD

**Issue by Johnnydoncom** [postaddictme/instagram-php-scraper#531] opened 2019-08-23 06:51 UTC
Please, I need help. I kept seeing **"Account with this username does not exist"** each time I run $instagram->getAccount($username);. The weird aspect of it is that, when I run the on localhost, it works well, but that's not the case when I upload to my remote server. I'm really confused. Please someone should help me out with a solution.

**Comment by Jurigag** [comment] 2019-08-23 07:37
Duplicate of #529

**Comment by jamalapriadi** [comment] 2019-10-09 03:11
i have same issue, but its work in my local computer and doesnt work in  my production server :(

**Comment by mnajafzadeh** [comment] 2019-12-13 08:40
Hi guys,

This problem is related to getAccount($username) function. You need to use searchAccountsByUsername($username) but, need to limit the results.
I try to do the change and create a pull request for limiting the results on this function.

**Comment by mnajafzadeh** [comment] 2019-12-13 08:57
Pull request created #578

**Closed** 2020-02-18 10:08 UTC
Labels: wontfix

**Comment by trebaxa** [comment] 2020-06-02 14:59
Workaround for me:
$instagram = new \InstagramScraper\Instagram();

                ```
    $account = $instagram->searchAccountsByUsername($this->gblconfig->insta_account);
                    $account = $account[0];
                    $nonPrivateAccountMedias = $instagram->getMediasByUserId($account->getId(), $ele_count, "");
```
